spring:
  application:
    name: skykyuu-backend
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: ${PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
